/**
 * A JSON Schema for `@drincs/pixi-vn`'s own `ContainerMemory` type, generated by
 * `scripts/generate-container-memory-schema.mjs` — see {@link containerMemorySchema}.
 */
export { containerMemorySchema } from "@/actions/container-memory-schema.generated";
